// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $sesion from "./routes/sesion.tsx";
import * as $MatchFetcher from "./islands/MatchFetcher.tsx";
import * as $Verificar from "./islands/Verificar.tsx";
import * as $inicio_Sesion from "./islands/inicio_Sesion.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/sesion.tsx": $sesion,
  },
  islands: {
    "./islands/MatchFetcher.tsx": $MatchFetcher,
    "./islands/Verificar.tsx": $Verificar,
    "./islands/inicio_Sesion.tsx": $inicio_Sesion,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
